### ISSUE TITLE
The esbuild JavaScript API cannot be bundled

### ISSUE THREAD

**Issue by vrabe** [wKovacs64/gatsby-plugin-use-dark-mode#114]
The build process got stuck in `Building development bundle` after I used this plugin. I found this exception when I was debugging:

>Error: The esbuild JavaScript API cannot be bundled. Please mark the "esbuild" package as external so it's not included in the bundle.
>
>More information: The file containing the code for esbuild's JavaScript API ([gatsby path]/.cache/page-ssr/routes/render-page.js) does not appear to be inside the esbuild package on the file system, which usually means that the esbuild package was bundled into another file. This is problematic because the API needs to run a binary executable inside the esbuild package which is located using a relative path from the API code to the executable. If the esbuild package is bundled, the relative path will be incorrect and the executable won't be found.
>
>at esbuildCommandAndArgs ([gatsby path]/.cache/page-ssr/routes/render-page.js:1917:11)
>at ensureServiceIsRunning ([gatsby path]/.cache/page-ssr/routes/render-page.js:2084:25)
>at startSyncServiceWorker ([gatsby path]/.cache/page-ssr/routes/render-page.js:2287:17)
>at Object../node_modules/esbuild/lib/main.js ([gatsby path]/.cache/page-ssr/routes/render-page.js:2328:3)
>at `__webpack_require__` ([gatsby path]/.cache/page-ssr/routes/render-page.js:7675:41)
>at Object../node_modules/gatsby-plugin-use-dark-mode/theme-hydration-script-tag.js ([gatsby path]/.cache/page-ssr/routes/render-page.js:2912:39)
>at `__webpack_require__` ([gatsby path]/.cache/page-ssr/routes/render-page.js:7675:41)
>at Object../node_modules/gatsby-plugin-use-dark-mode/gatsby-ssr.js ([gatsby path]/.cache/page-ssr/routes/render-page.js:2818:55)
>at `__webpack_require__` ([gatsby path]/.cache/page-ssr/routes/render-page.js:7675:41)
>at Object../.cache/api-runner-ssr.js ([gatsby path]/.cache/page-ssr/routes/render-page.js:2432:11)

**Comment by wKovacs64** [comment]
Well shoot... sorry about that, I'll fix this shortly. Thanks for the report!

**Comment by wKovacs64** [comment]
@vrabe I reverted the esbuild change and published `gatsby-plugin-use-dark-mode@1.5.0`.

**Comment by vrabe** [comment]
Thank you for fixing it! I am going to close this issue.
