### ISSUE TITLE
Website crashes when the value of darkMode in LocalStorage is undefined

### ISSUE THREAD

**Issue by Talaxy009** [wKovacs64/gatsby-plugin-use-dark-mode#145]
I encountered a crash problem today and found that other plugins accidentally changed the value of darkMode to `undefined`. Although I've fixed the issue, the user has to clear the website cache to reset the drakMode value and get the website to work. So I thought it would be perfect if gatsby-plugin-use-dark-mode could handle this unexpected situation. 

The steps to reproduce:
- Running `localStorage.setItem('darkMode', 'undefined');` in the console to simulate unexpected situations.
- Reloading the website then you should be able to see something like the image below:

![image](https://user-images.githubusercontent.com/41264828/218450791-ff03c668-3280-4b0c-9565-144871854143.png)

**Comment by wKovacs64** [comment]
Thanks @Talaxy009!

**Comment by tholyong** [comment]
@Talaxy009  May I know what plugin causes the issue? I recently found that similar issue but couldn't figure out why the value is replaced with "undefined"? I just updated Gatsby to version 5.7.0 and the issue come out.

**Comment by Talaxy009** [comment]
@tholyong I have written an [article](https://www.talaxy.site/valine-affect-darkmode/) about  this issue, but it is Chinese. Here's what I found, the problem happens because use-dark-mode listens to an input element (I think it's a problem with use-dark-mode because it should listen to `prefers-color-scheme` media but it doesn't), when the input value change, it will set the localStorage as `undefined` because the event object is different. To fix it you can remove all `@media(prefers-color-scheme: dark)` styles in your site or write your "use-dark-mode", I write mine [here](https://github.com/Talaxy009/my-gatsby-blog/blob/main/src/utils/darkMode.tsx), the use method is different but the base logic is same so the gatsby-plugin-use-dark-mode still work.

If you're curious which element is causing it, you can locate the element with these codes:

```js
// save the orignal setItem method
const orignalSetItem = localStorage.setItem;

// rewrite setItem, it will dispatch a event when called
localStorage.setItem = function (key, newValue) {
    let setItemEvent = new Event('setItemEvent');
    setItemEvent.newValue = newValue;
    setItemEvent.key = key;
    window.dispatchEvent(setItemEvent);
    orignalSetItem.apply(this, arguments);
};

// throw an error when the event dispatched
window.addEventListener('setItemEvent', function (e) {
    throw e;
});
```
and you might see something like this:
![ss02](https://user-images.githubusercontent.com/41264828/223095874-07bf1d80-dd95-4a15-88c4-bd3d5a0cc70c.png)

**Comment by tholyong** [comment]
Thank you for the information and also the solution! This is exactly the issue I'm facing. I think I'm gonna write my own useDarkMode as you suggested.

**Comment by Talaxy009** [comment]
You are welcome☺️
