### ISSUE TITLE
Compatibility with PrimeReact

### ISSUE THREAD

**Issue by inzsome** [wKovacs64/gatsby-plugin-use-dark-mode#157]
I'm currently using the component library [PrimeReact](https://primereact.org/installation/) to display a switch in my app.

I'm also using an input field in my app.
If I type something in the input field and press enter, the theme reverts to light mode and the localeStorage value is set to `undefined`.

I know this might not be the fault of your plugin, but maybe you could help me figure out what the problem is, or maybe even fix it.

Here's a minimal example to reproduce the issue: https://codesandbox.io/p/sandbox/clever-curran-kzmyhg?file=%2Fsrc%2Fcomponents%2Ftheme-switch.js%3A12%2C82

Edit: I don't think it's a problem with PrimeReact. I removed every PrimeReact component, including the `ThemeProvider`, but the issue still persists:
https://codesandbox.io/p/sandbox/dank-sea-3jvvdh?file=%2Fsrc%2Fpages%2Findex.js%3A3%2C50

Thanks in advance!

**Comment by wKovacs64** [comment]
Did you figure this out?

**Comment by inzsome** [comment]
Sorry for keeping you waiting for my response. In the meantime, I tried other forks, but the issue persisted throughout every single one.

I finally sorted it out by using a different plugin: https://github.com/zeinhajjali/gatsby-plugin-dark-mode

Thank you, though.

**Comment by wKovacs64** [comment]
Cool, glad you found a solution. 👍
