### ISSUE TITLE
noflash.js could get out of sync

### ISSUE THREAD

**Issue by donavon** [wKovacs64/gatsby-plugin-use-dark-mode#3]
in `theme-hydration-script-tag.js` you've replicated the code for `noflash.js.txt`. I'd much rather see this come directly from `use-dark-mode` (which you already have as a peerDependency). This will require some cooperation on the `use-dark-mode` side by making the understanding that changing the default variable names is a breaking change. i.e. these names MUST NOT change in any `^2.x.x`.

```js
var storageKey = 'darkMode';
var classNameDark = 'dark-mode';
var classNameLight = 'light-mode';
```

You could then import from `noflash.js.txt` and perform some RegEx magic based on the `ThemeHydrationScriptTag ` props.

**Comment by wKovacs64** [comment]
Yeah, definitely - I would love to sync this up.

**Comment by wKovacs64** [comment]
@donavon What do you think of the following? In the `use-dark-mode` project, we could:

1. Create and expose a `generateNoFlashScriptText` utility function that takes in the config options and returns the final IIFE string with the options passed in.
2. Add a tiny build step that writes the result to `noflash.js.txt`.

Then external projects like this one can import `generateNoFlashScriptText` and pass in their own option values and do whatever they need to with the results.

I have this working locally, but it's obviously adding a little clutter to the `use-dark-mode` repo as opposed to just making downstream consumers import `noflash.js.txt` directly and perform some search-and-replace. It feels less brittle than regexes, but you're still beholden to the field names in the `options` object (or argument order if you prefer individual parameters). Not sure it's worth it. Thoughts?

---

Usage:
```js
generateNoFlashScriptText({
  storageKey: 'darkMode',
  classNameDark: 'dark-mode',
  classNameLight: 'light-mode',
});
```
Return value (string):
```
// Insert this script in your index.html right after the <body> tag.
// This will help to prevent a flash if dark mode is the default.

(function(options) {
  var storageKey = options.storageKey;
  var classNameDark = options.classNameDark;
  var classNameLight = options.classNameLight;

  function setClassOnDocumentBody(darkMode) {
    document.body.classList.add(darkMode ? classNameDark : classNameLight);
    document.body.classList.remove(darkMode ? classNameLight : classNameDark);
  }

  var preferDarkQuery = '(prefers-color-scheme: dark)';
  var mql = window.matchMedia(preferDarkQuery);
  var supportsColorSchemeQuery = mql.media === preferDarkQuery;
  var localStorageTheme = null;
  try {
    localStorageTheme = localStorage.getItem(storageKey);
  } catch (err) {}
  var localStorageExists = localStorageTheme !== null;
  if (localStorageExists) {
    localStorageTheme = JSON.parse(localStorageTheme);
  }

  // Determine the source of truth
  if (localStorageExists) {
    // source of truth from localStorage
    setClassOnDocumentBody(localStorageTheme);
  } else if (supportsColorSchemeQuery) {
    // source of truth from system
    setClassOnDocumentBody(mql.matches);
    localStorage.setItem(storageKey, mql.matches);
  } else {
    // source of truth from document.body
    var isDarkMode = document.body.classList.contains(classNameDark);
    localStorage.setItem(storageKey, JSON.stringify(isDarkMode));
  }
})({
  // Change these if you use something different in your hook.
  storageKey: 'darkMode',
  classNameDark: 'dark-mode',
  classNameLight: 'light-mode'
});
```

Build step:
```js
const fs = require('fs');
const generateNoFlashScriptText = require('./generate-noflash-script-text');

fs.writeFileSync('./noflash.js.txt', generateNoFlashScriptText());
```

**Comment by wKovacs64** [comment]
Any thoughts on the above, @donavon? Low priority, of course. 🙂
