### ISSUE TITLE
Flashing when using with styled-components

### ISSUE THREAD

**Issue by talohana** [wKovacs64/gatsby-plugin-use-dark-mode#58]
I am using styled-components and use-dark-mode with default config, both the plugin and the hook itself.
When dark mode is enabled and I refresh the page I still get colors flashing.

I have a Layout.tsx component that includes:

```tsx
const GlobalStyles = createGlobalStyle`
    body {
        transition: all 0.5s linear;

        &.dark-mode {
          background-color: #1f1f1f;
          color: #dfe6e9;
        }

        &.light-mode {
          background-color: #ecf0f1;
          color: #1f1f1f;
        }
    }
`
```

which is then included in the layout component:
```tsx
export const Layout = ({ children }) => {
    <div>
        <GlobalStyles />
        {children}
    </div>
}
```

**Comment by wKovacs64** [comment]
Hey @talohana! 👋 

I'm not a styled-components user so I'm not sure if there's anything special you need to do to make it work with Gatsby (particularly with regards to SSR) beyond following all the steps in the [Gatsby styled-components documentation](https://www.gatsbyjs.com/docs/styled-components/) (using `gatsby-plugin-styled-components`, etc.). I do know there are open [issues](https://github.com/styled-components/styled-components/issues/2629) about this type of thing, specifically around Gatsby and styled-components, but I have no first-hand experience with it.

Is your project public, by chance? If not, could you make a small reproduction of the issue for me? I'm pretty busy with work right now but I will try to help if you can provide a project.

Side note: I'm currently using this plugin (coupled with `use-dark-mode`) successfully with Emotion, but I know that doesn't help you - just another data point.

**Comment by talohana** [comment]
> Hey @talohana! 👋
> 
> I'm not a styled-components user so I'm not sure if there's anything special you need to do to make it work with Gatsby (particularly with regards to SSR) beyond following all the steps in the [Gatsby styled-components documentation](https://www.gatsbyjs.com/docs/styled-components/) (using `gatsby-plugin-styled-components`, etc.). I do know there are open [issues](https://github.com/styled-components/styled-components/issues/2629) about this type of thing, specifically around Gatsby and styled-components, but I have no first-hand experience with it.
> 
> Is your project public, by chance? If not, could you make a small reproduction of the issue for me? I'm pretty busy with work right now but I will try to help if you can provide a project.
> 
> Side note: I'm currently using this plugin (coupled with `use-dark-mode`) successfully with Emotion, but I know that doesn't help you - just another data point.

My code isn't public but I quickly reproduced in [talohana/dark-mode-reproduction](https://github.com/talohana/dark-mode-reproduction).

Just to make sure I'm not confusing things, the `noflash.js` should also not show the `transition: all 0.5s linear`?
I expected the transition won't happen on initial loading.

If any PR is required I'd be happy to help
Thank you for your time!

**Comment by wKovacs64** [comment]
Ah okay, it's the transition that's the problem. So all `noflash.js` does is determine the user's dark/light mode preference (either from a previously saved setting in localStorage or from the user's system preferences) and then apply the corresponding class to the `<body>` element. And all `gatsby-plugin-use-dark-mode` does is insert that code at the top of `<body>` via the Gatsby SSR API (so it runs before your content shows up).

As you have it currently, the transition will happen on page load (nothing to do with `use-dark-mode` or `gatsby-plugin-use-dark-mode`, really). If you want to keep the transition for when a user toggles modes but not show it on initial page load, I think you'd have to do something like this: https://css-tricks.com/transitions-only-after-page-load/
