### ISSUE TITLE
Compatibility with Gatsby v3

### ISSUE THREAD

**Issue by kelvindecosta** [wKovacs64/gatsby-plugin-use-dark-mode#73]
## Overview

Gatsby recently released version 3.
This plugin breaks and throws a few warnings and error messages.

## Behavior

When running the development server, the following warning messages are displayed:

```
warn Plugin gatsby-plugin-use-dark-mode is not compatible with your gatsby version 3.0.3 - It requires gatsby@^2.0.0
```

When using the `useDarkMode` hook within a component, the following errors are logged into the browser's console:

```
Uncaught ReferenceError: global is not defined
    at d (use-dark-mode.m.js:1)
```

## Environment

<details>

<summary>

`gatsby info`

</summary>

```
  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 3.9.1 - /usr/bin/python
  npmPackages:
    gatsby: ^3.0.3 => 3.0.3
    gatsby-plugin-image: ^1.0.0 => 1.0.0
    gatsby-plugin-layout: ^2.0.0 => 2.0.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-mdx: ^2.0.0 => 2.0.0
    gatsby-plugin-netlify: ^3.0.0 => 3.0.0
    gatsby-plugin-no-sourcemaps: ^3.0.0 => 3.0.0
    gatsby-plugin-nprogress: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-preact: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-remove-trailing-slashes: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0
    gatsby-plugin-use-dark-mode: ^1.2.0 => 1.2.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 2.19.1
```

</details>

## Conclusion

The plugin breaks when upgrading Gatsby to v3.
Please refer to [this section, addressed to plugin maintainers, in the migration guide for Gatsby v3](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers).

Thank you for actively maintaining this project!

**Comment by kelvindecosta** [comment]
I'm sorry, I didn't notice the update.

Thanks again!

**Comment by wKovacs64** [comment]
Hey @kelvindecosta, no worries! Thanks.

**Comment by kelvindecosta** [comment]
Sorry again @wKovacs64, I think the issue isn't resolved.

I'm getting the same error even after updating to `1.3.0`.

![Screenshot of error](https://user-images.githubusercontent.com/38982451/110195912-cbb4b300-7e51-11eb-8702-21444b75cc8a.png)

**Comment by wKovacs64** [comment]
Yeah, unfortunately that's coming from https://github.com/donavon/use-dark-mode rather than this plugin. I'm not near the computer at the moment to confirm, but I don't think this is anything I can address. 😕

**Comment by kelvindecosta** [comment]
Ah, that's alright! Thank you for your help with this matter and for this nice plugin!

**Comment by wKovacs64** [comment]
No sweat, thanks for your interest!

**Comment by kelvindecosta** [comment]
Hey!

I did some research and I figured that the bug is caused by some changes made to the webpack configuration (see index webpack/webpack#10035).

Still haven't found a clean solution.

**Comment by wKovacs64** [comment]
It appears Donavon is using `global` in several of his packages including `use-dark-mode`. I actually had an unrelated project break because it was using one of his libraries as a dependency and it was throwing the same error you're getting.

I'm not sure of the "correct" fix. Does Gatsby v3 need to change how they're using webpack 5? Does `use-dark-mode` need to use something other than `global` (`window`? `globalThis` is probably best but it would break IE 11?)? Something else entirely?

I _could_ throw in a hacky workaround in this plugin temporarily but that probably isn't the best long-term solution. 🤔

**Comment by wKovacs64** [comment]
Hey @kelvindecosta I have a couple demo projects using `gatsby-plugin-use-dark-mode`, `use-dark-mode`, and Gatsby v3 and they are both working, actually.

Example: https://codesandbox.io/s/gatsby-plugin-use-dark-mode-tzz2q

**Comment by kelvindecosta** [comment]
Hey!

I tried adding `node : {global : true}` to the webpack config (via Gatsby Node API) and I don't think it made a difference to the `polyfill.js` script.

I noticed that on the CodeSandbox and on my local project, the `global` is undefined but `globalThis` exists instead.

**Comment by wKovacs64** [comment]
`global` is a Node thing, and I think Webpack 4 defaulted to polyfilling Node globals (or everyone enabled it). Webpack 5 doesn't, which is where I assumed the problem came in - but now I'm not exactly sure since I have a couple working examples where I didn't change that.

Libraries targeting the browser like `use-dark-mode` probably shouldn't use `global`, they should probably use `window` (or `globalThis` if not supporting IE, maybe). 🤔 Interestingly, it appears the `useDarkMode()` hook accepts an undocumented `global` configuration option, so you could try this just for fun:

```
const darkMode = useDarkMode(false, { global: globalThis })
```

---

Some interesting reads:

https://blog.logrocket.com/what-is-globalthis-why-use-it/
https://mathiasbynens.be/notes/globalthis

**Comment by kelvindecosta** [comment]
Hey!

Thanks for the information about `global`.
I am yet to try the fix you described.

Here is a minimal reproduction on [CodeSandbox with the default starter](https://codesandbox.io/s/use-dark-mode-wgatsby-v3-kd7cb).

I think it has to do with React v17? That seems to be the main difference between our sandboxes.

**Comment by wKovacs64** [comment]
Oh, good catch. I'll try to play around more tomorrow.

**Comment by wKovacs64** [comment]
Technically, `use-dark-mode` doesn't support React 17 (based on their `peerDependencies`), but it seems to work. I forked my own example and updated React and it still works: https://codesandbox.io/s/gatsby-plugin-use-dark-mode-forked-t7hn7

That reproduction you linked doesn't even load for me (crashes in CSB). Is that where you saw the unhandled runtime error before, or was it in your real project?

I'm interested to hear if specifying `{ global: globalThis }` fixes it for you as I don't think there's anything this plugin can/should do to address it. 😕

**Comment by kelvindecosta** [comment]
I just looked at my reproduction again, and it crashes for me as well.
I'm not quite sure what happened.
I will create another reproduction when I get free.

I tried using the `{ global: globalThis }` fix, and I get the same error.

I think I might have upgraded some dependencies poorly while migrating from Gatsby v2 to v3.
If it works with React v17 then there's nothing wrong with the plugin but rather there's something wrong with my setup.

**Comment by kelvindecosta** [comment]
Hey @wKovacs64 

Sorry for the delay.

I created a reproduction [here](https://codesandbox.io/s/use-dark-mode-wgatsby-v3-mb3wf) by performing the following steps:

- Start with Gatsby Default Starter.
-  `yarn add gatsby-plugin-use-dark-mode use-dark-mode`.
- `yarn upgrade`, for `gatsby: 3.0.3`.
- Add `gatsby-plugin-use-dark-mode` in plugins list.
- Invoke `useDarkMode` hook in the `Layout` component, destructure `value` and display it.

The same error as usual. 😕

**Comment by kelvindecosta** [comment]
So, I decided to use just `gatsby-plugin-use-dark-mode` in my list of plugins.
I kept adding back the plugins one by one.

Pretty sure `gatsby-plugin-image` is causing the issue.
I tried changing the order of the plugins and that didn't make any difference.

**Comment by wKovacs64** [comment]
Interesting! I wonder what `gatsby-plugin-image` could be doing to break unrelated plugins like that... how strange.

Thanks for your efforts troubleshooting this!
