### ISSUE TITLE
Requires 2 clicks when reload on darkMode.value true

### ISSUE THREAD

**Issue by yudyananda** [wKovacs64/gatsby-plugin-use-dark-mode#78]
Hi, not sure if i can address my issue to `gatsby-plugin-use-dark-mode` but the input toggle seems failed. It requires 2 click when the `darkMode.value` state is `true`. Strangely it works fine on button—*disable, enable dan toggle* . The issue occurs in dev and build version. 

```js
import * as React from 'react';
import useDarkMode from 'use-dark-mode';

const DarkmodeToggle = () => {
    
    const { enable, disable, toggle, value } = useDarkMode(false)
    
    return (
        <span className="toggle-control">
            <button className="button" onClick={disable}>☀</button>
            <input
                aria-label="Toggle Dark Mode"
                id="dmcheck"
                className="dmcheck"
                type="checkbox"
                checked={value}
                onChange={toggle}
            />  
            <label htmlFor="dmcheck" />
            <button className="button" onClick={enable}>☾</button>
        </span>
    )
}

export default DarkmodeToggle
```
```
gatsby: ^3.4.0
gatsby-plugin-use-dark-mode: ^1.3.0
use-dark-mode: ^2.3.1
```
kindly close this thread if you think this is not related to this plugin. thanks

**Comment by wKovacs64** [comment]
Hi @yudyananda!

I don't think it's an issue with this plugin as I have several working demos using the same versions you mentioned. I might be able to help if I could see a reproduction of the problem, though (CodeSandbox or a repo)?

**Comment by yudyananda** [comment]
Sure, here is the [repo](https://github.com/yudyananda/use-dark-mode-click-twice-on-dark) i wonder if this could be a mistake from my code for passing the wrong props on `onChange` attribute

**Comment by wKovacs64** [comment]
Interesting, it seems to be an SSR issue. Others have reported similar problems in the use-dark-mode repo. (If you change the `DEV_SSR` Gatsby feature flag to false, development will function as you'd expect - but you shouldn't have to do that.) And I just confirmed it in a couple of my "working" demos. 😅 

This isn't an issue with `gatsby-plugin-use-dark-mode` but I'm interested in a solution. One option would be to only render the toggle client-side, but that might be a bit of a hack.

**Comment by yudyananda** [comment]
I see, thanks for the confirmation. the only workaround is to avoid using input or simply use it as button not checkbox. I guess the [`toggle`](https://github.com/donavon/use-dark-mode/blob/29590271bb3a74f08975181c5ed68bd5a210ef83/src/index.js#L51) from `use-dark-mode` didn't work with `onChange`

**Comment by wKovacs64** [comment]
Hey @yudyananda check it out... if you delay rendering of the toggle until the client has hydrated, it works as expected (perhaps this is acceptable in your project, perhaps not):

```diff
diff --git a/src/components/Toggle/ToggleDarkMode.js b/src/components/Toggle/ToggleDarkMode.js
index 2394ad22..0ab53337 100644
--- a/src/components/Toggle/ToggleDarkMode.js
+++ b/src/components/Toggle/ToggleDarkMode.js
@@ -14,7 +14,7 @@ const DarkmodeToggle = () => {
     
     const { toggle, value } = useDarkMode(false)
 
-    
+    if (typeof window === 'undefined') return null;
     
     return (
         <Toggle className="toggle-control">
```

If you're interested in the problem space, check out this excellent article by Josh W. Comeau:

https://www.joshwcomeau.com/react/dark-mode/

**Comment by yudyananda** [comment]
Aha, it works like a charm. So this will make toggle render in the client right? Thanks, i really appreciate your help

**Comment by wKovacs64** [comment]
Yeah, it just renders nothing in the static/server-rendered markup. Then when the JS loads and hydrates (client-side), it renders the toggle. And by that time, it can know the correct state of the toggle, so it doesn't start out of sync.
